### ISSUE TITLE
Create Gameplay flow

### ISSUE THREAD

**Issue by MinhPhan23** [MikeAfterDark/CSSA2024#18]
We want to create a flow like the following:
- Load in Manager scene to initiate Manager Scripts, then immediately load into Menu
- Load into Loading Screen (if needed)
- Load into Game
- When end, back to menu

**Comment by MikeAfterDark** [comment]
These are all completed except the 'go back to menu' which just needs a 
`GameManager.Instance.UpdateGameState(GameManager.GameState.MainMenu);` event trigger at some point when the game is 'ended'
